In [1]:
import pandas as pd

In [3]:
small_train_path = './nobias_train_e3_smallscale.csv'
small_val_path = './nobias_val_e3_smallscale.csv'

nobias_train_path = './nobias_train_e3.csv'
nobias_val_path = './nobias_val_e3.csv'

bias_train_path = './bias_train_e3.csv'
bias_val_path = './bias_val_e3.csv'

In [11]:
data_train = pd.read_csv(nobias_train_p)
data_val = pd.read_csv(bias_val_path)

In [17]:
data_train

,gamma1,lambda1,delta,epsilon,NRow,NCol,FValue,W1
0,0.013904,0.042775,77.038107,44.164476,0.001251,0.000453,-5.885985e-10,1.090753e-08
1,0.026082,0.022650,90.304047,38.716104,0.001097,0.000963,-2.128956e-09,4.110760e-07
2,0.000120,0.099312,31.834305,98.744596,0.001922,0.000107,5.109891e-09,4.588245e-06
3,0.027485,0.016756,21.663728,74.636281,0.002397,0.000886,-2.129813e-09,6.411097e-12
4,0.003945,0.044921,30.256109,47.186502,0.000290,0.000445,-4.165267e-10,2.146103e-06
...,...,...,...,...,...,...,...,...
995,0.004036,0.010596,72.691182,28.712080,0.002873,0.000436,7.003548e-10,8.064674e-09
996,0.035617,0.025967,15.817668,13.564346,0.000198,0.001053,-2.256313e-09,1.154501e-07
997,0.001074,0.053878,77.289542,52.242338,0.001015,0.001365,-3.583264e-10,1.225554e-06
998,0.000076,0.060447,47.836039,23.508705,0.000564,0.000140,1.410783e-09,6.286568e-06
999,0.019917,0.023296,83.018568,99.217623,0.000588,0.001094,-2.678767e-09,2.942430e-10

In [19]:
data_val

,gamma1,lambda1,delta,epsilon,NRow,NCol,FValue,W1
0,0.000665,0.015316,33.553512,70.543269,0.001392,0.000909,-4.490235e-11,3.582399e-07
1,0.035572,0.034826,32.228092,81.701326,0.000298,0.002217,-5.996781e-09,1.561656e-11
2,0.007851,0.074636,91.562912,32.542111,0.000507,0.000757,-9.194075e-10,8.379834e-07
3,0.003126,0.053979,32.459158,66.238669,0.000739,0.001141,-2.073341e-09,1.965047e-07
4,0.000147,0.064056,34.475475,61.457138,0.000097,0.000639,-9.841668e-10,4.802954e-06
...,...,...,...,...,...,...,...,...
995,0.000094,0.045389,87.876618,49.789633,0.000705,0.001476,2.188299e-09,7.663847e-06
996,0.028243,0.090493,24.154589,40.096106,0.001271,0.003030,-8.094616e-09,3.100623e-11
997,0.000129,0.011721,37.880907,45.511508,0.000237,0.000258,4.096430e-11,1.758468e-06
998,0.035455,0.011404,36.104098,57.694653,0.001302,0.000959,-2.327713e-09,2.270106e-11
999,0.001089,0.019151,88.427263,24.523062,0.000856,0.002929,-8.253427e-10,7.023903e-07